/**
 * POC: Design-to-Code Visual Comparison Test
 *
 * Validates the visual comparison pipeline:
 *   Design screenshot → Code generation → Implementation screenshot → Diff
 *
 * Smoke test strategy:
 *   Components 1-3: Full L1+L2+L3 (calibrate baseline)
 *   Components 4+:  L1+L2 only (save cost)
 *   Full page:      L1+L2+L3 (final gate)
 *
 * Prerequisites:
 *   - npm install pixelmatch pngjs (for pixel comparison)
 *   - Design reference screenshots in tests/visual-diff/references/
 *   - Frontend running at localhost:3000
 *
 * Author: browser-tester
 * Date: 2026-02-14
 */

import { test, expect } from '@playwright/test';
import {
  compareComponent,
  formatForSSE,
  type CompareOptions,
  type VisualDiffResult,
} from './visual-comparator';

// --- Configuration ---

const DESIGN_REFERENCES_DIR = 'tests/visual-diff/references';
const RESULTS: VisualDiffResult[] = [];

/**
 * Component manifest for POC.
 *
 * In the full pipeline, this would be auto-generated by Node 1 (Design Analyzer).
 * For POC, we manually define the components to test.
 */
const POC_COMPONENTS: Array<{
  id: string;
  name: string;
  selector: string;
  designFile: string;
  isSmoke: boolean; // true for first 3 components (full L1+L2+L3)
  expectedStructure?: {
    elementCount: number;
    layoutDirection?: 'row' | 'column' | 'grid';
    requiredChildren?: string[];
  };
}> = [
  // TODO: Fill in actual component selectors from the generated code
  // These are placeholders showing the expected format
  {
    id: 'sidebar',
    name: 'Sidebar Navigation',
    selector: '[data-testid="sidebar"]',
    designFile: `${DESIGN_REFERENCES_DIR}/sidebar.png`,
    isSmoke: true, // Component 1 — full verification
    expectedStructure: {
      elementCount: 3,
      layoutDirection: 'column',
      requiredChildren: ['[data-testid="logo"]', 'nav'],
    },
  },
  {
    id: 'header',
    name: 'Page Header',
    selector: '[data-testid="header"]',
    designFile: `${DESIGN_REFERENCES_DIR}/header.png`,
    isSmoke: true, // Component 2 — full verification
    expectedStructure: {
      elementCount: 2,
      layoutDirection: 'row',
    },
  },
  {
    id: 'main-card',
    name: 'Main Content Card',
    selector: '[data-testid="main-card"]',
    designFile: `${DESIGN_REFERENCES_DIR}/main-card.png`,
    isSmoke: true, // Component 3 — full verification (last smoke test)
  },
  {
    id: 'stats-panel',
    name: 'Statistics Panel',
    selector: '[data-testid="stats-panel"]',
    designFile: `${DESIGN_REFERENCES_DIR}/stats-panel.png`,
    isSmoke: false, // Component 4+ — L1+L2 only
  },
  {
    id: 'footer',
    name: 'Footer Section',
    selector: '[data-testid="footer"]',
    designFile: `${DESIGN_REFERENCES_DIR}/footer.png`,
    isSmoke: false, // Component 5 — L1+L2 only
  },
];

// --- Tests ---

test.describe('Design-to-Code POC: Visual Comparison', () => {
  test.beforeAll(async () => {
    // TODO: Ensure design reference screenshots exist
    // In the full pipeline, these come from Figma/Pencil MCP get_screenshot()
  });

  for (const component of POC_COMPONENTS) {
    test(`Component: ${component.name} (${component.isSmoke ? 'smoke L1+L2+L3' : 'L1+L2'})`, async ({
      page,
    }) => {
      // Navigate to the generated page
      // TODO: Update URL to the actual generated page path
      await page.goto('/test-harness/design-poc');

      const options: CompareOptions = {
        componentId: component.id,
        selector: component.selector,
        designScreenshotPath: component.designFile,
        runAIComparison: component.isSmoke, // L3 only for smoke test components
        viewport: { width: 1440, height: 900 },
      };

      const result = await compareComponent(
        page,
        options,
        component.expectedStructure
      );

      // Collect results for summary
      RESULTS.push(result);

      // Log SSE-formatted event (for pipeline integration)
      const sseEvent = formatForSSE(result);
      console.log(`[visual-diff] ${JSON.stringify(sseEvent)}`);

      // Assertions
      if (component.isSmoke) {
        // Smoke test: strict — must pass structure + pixel diff
        expect(result.structureCheck.passed, 'Structure check failed').toBe(
          true
        );
        expect(
          result.pixelDiff.diffPercentage,
          `Pixel diff ${result.pixelDiff.diffPercentage}% exceeds threshold`
        ).toBeLessThan(15);
        expect(result.verdict).not.toBe('fail');
      } else {
        // Non-smoke: structure must pass, pixel diff informational
        expect(result.structureCheck.passed, 'Structure check failed').toBe(
          true
        );
      }
    });
  }

  test('Full page: Assembly verification (L1+L2+L3)', async ({ page }) => {
    await page.goto('/test-harness/design-poc');

    // Full page screenshot comparison
    const result = await compareComponent(page, {
      componentId: 'full-page',
      selector: 'body',
      designScreenshotPath: `${DESIGN_REFERENCES_DIR}/full-page.png`,
      runAIComparison: true, // Always run AI for full page
      viewport: { width: 1440, height: 900 },
    });

    RESULTS.push(result);
    console.log(`[visual-diff] ${JSON.stringify(formatForSSE(result))}`);

    // Full page must pass
    expect(result.verdict, 'Full page visual diff failed').not.toBe('fail');
  });

  test.afterAll(async () => {
    // Print summary
    console.log('\n=== Visual Diff Summary ===');
    for (const r of RESULTS) {
      const icon =
        r.verdict === 'pass' ? '✅' : r.verdict === 'fail' ? '❌' : '⚠️';
      console.log(
        `${icon} ${r.componentId}: ${r.verdict} (pixel diff: ${r.pixelDiff.diffPercentage}%)`
      );
    }

    const passed = RESULTS.filter((r) => r.verdict === 'pass').length;
    const failed = RESULTS.filter((r) => r.verdict === 'fail').length;
    const review = RESULTS.filter((r) => r.verdict === 'needs_review').length;
    console.log(`\nTotal: ${passed} pass, ${failed} fail, ${review} review`);
    console.log('========================\n');
  });
});
